db-drop:
	./migrate -path ./migrations -database 'postgres://aaron:newpa4s1@localhost:5432/madimage?sslmode=disable' drop -f

db-migrate:
	./migrate -path ./migrations -database 'postgres://aaron:newpa4s1@localhost:5432/madimage?sslmode=disable' up 